<?php
/**
 * Encryption Service
 *
 * Provides AES-256-GCM authenticated encryption/decryption for sensitive
 * credentials such as SMTP passwords.
 *
 * Format: hex(iv):hex(tag):hex(ciphertext). GCM is authenticated (AEAD):
 * the 16-byte tag is produced by openssl_encrypt() and verified by openssl_decrypt(),
 * so any tampering with the stored ciphertext makes decrypt() return false rather
 * than returning altered plaintext.
 *
 * All consumers across the free and pro plugins call this single service. The key is
 * derived at runtime from WordPress's own secret salts via wp_salt(); it is never
 * generated by the plugin nor stored in the database. Because the key follows the
 * site's secret salts, regenerating those salts (a security reset, or moving to an
 * environment with a different wp-config.php) makes previously stored values
 * undecryptable; callers treat that as "not set" and prompt the admin to re-enter,
 * exactly as they would on a fresh install.
 *
 * @package    Tailwatch
 * @subpackage Services/Crypto
 */

namespace Tailwatch\Admin\App\Api\Services\Crypto;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class EncryptionService {

	const CIPHER     = 'aes-256-gcm';
	const IV_LENGTH  = 12; // 96-bit nonce: the recommended IV size for GCM.
	const TAG_LENGTH = 16; // 128-bit authentication tag.

	/**
	 * Encrypt sensitive data using AES-256-GCM (authenticated).
	 *
	 * @param string $data Plaintext data to encrypt.
	 * @return string|false Hex-encoded "iv:tag:ciphertext" string; the original value
	 *                unchanged if the encryption key is unavailable; or false if the
	 *                cipher itself fails (so a caller never silently persists plaintext).
	 */
	public static function encrypt( $data ) {
		if ( empty( $data ) ) {
			return $data;
		}

		$key = self::get_key();
		if ( ! $key ) {
			return $data;
		}

		$iv  = random_bytes( self::IV_LENGTH );
		$tag = '';
		// $tag is passed by reference: openssl_encrypt() writes the GCM auth tag into it.
		$ciphertext = openssl_encrypt( $data, self::CIPHER, $key, OPENSSL_RAW_DATA, $iv, $tag, '', self::TAG_LENGTH );

		if ( false === $ciphertext ) {
			return false;
		}

		// Format: hex(iv):hex(tag):hex(ciphertext).
		return bin2hex( $iv ) . ':' . bin2hex( $tag ) . ':' . bin2hex( $ciphertext );
	}

	/**
	 * Decrypt data encrypted by encrypt().
	 *
	 * @param string $data Encrypted string in "hex(iv):hex(tag):hex(ciphertext)" format.
	 * @return string|false Decrypted plaintext, or false if the value is not in GCM
	 *                      format, the tag fails verification, or decryption fails.
	 */
	public static function decrypt( $data ) {
		if ( empty( $data ) || ! is_string( $data ) ) {
			return false;
		}

		$parts = explode( ':', $data );
		if ( count( $parts ) !== 3 ) {
			return false; // Not GCM format.
		}

		// Validate the hex before hex2bin(), which emits a warning on malformed input.
		if ( ! self::is_hex_bytes( $parts[0], self::IV_LENGTH )
			|| ! self::is_hex_bytes( $parts[1], self::TAG_LENGTH )
			|| ! ctype_xdigit( $parts[2] ) || 0 !== strlen( $parts[2] ) % 2 ) {
			return false;
		}

		$key = self::get_key();
		if ( ! $key ) {
			return false;
		}

		$iv  = hex2bin( $parts[0] );
		$tag = hex2bin( $parts[1] );
		$ct  = hex2bin( $parts[2] );

		// openssl_decrypt() verifies $tag; returns false if the ciphertext was tampered with.
		$plaintext = openssl_decrypt( $ct, self::CIPHER, $key, OPENSSL_RAW_DATA, $iv, $tag );
		return ( false !== $plaintext ) ? $plaintext : false;
	}

	/**
	 * Check whether a string is in this service's encrypted (GCM) format.
	 *
	 * @param string $data Value to test.
	 * @return bool True if the value matches the "hex(iv):hex(tag):hex(ct)" format.
	 */
	public static function is_encrypted( $data ) {
		if ( empty( $data ) || ! is_string( $data ) ) {
			return false;
		}
		$parts = explode( ':', $data );
		if ( count( $parts ) !== 3 ) {
			return false;
		}
		return self::is_hex_bytes( $parts[0], self::IV_LENGTH )
			&& self::is_hex_bytes( $parts[1], self::TAG_LENGTH );
	}

	/**
	 * Whether a value is exactly $byte_len bytes encoded as hex.
	 *
	 * @param mixed $hex      Value to test.
	 * @param int   $byte_len Expected decoded length in bytes.
	 * @return bool
	 */
	private static function is_hex_bytes( $hex, $byte_len ) {
		return is_string( $hex ) && strlen( $hex ) === $byte_len * 2 && ctype_xdigit( $hex );
	}

	/**
	 * Get the encryption key, derived to 32 bytes via SHA-256.
	 *
	 * The key is derived from WordPress's own secret salts (wp_salt()), which live in
	 * wp-config.php on a standard install. This keeps the key out of the plugin's
	 * database tables, so a database dump alone cannot decrypt stored secrets, and the
	 * plugin never has to generate, store, or write a key of its own.
	 *
	 * @return string|false 32-byte binary key or false if unavailable.
	 */
	private static function get_key() {
		if ( ! function_exists( 'wp_salt' ) ) {
			return false;
		}
		$salt = wp_salt( 'secure_auth' );
		if ( empty( $salt ) ) {
			return false;
		}
		return hash( 'sha256', 'tailwatch-encryption|' . $salt, true );
	}
}
