export const bgprimary = "bg-[#007980]";
export const iconprimary = "text-[#007980]";
export const bgdarkGray = "bg-gray-400";
export const lightGray = "#e5e7eb";
export const primaryGradient = "bg-gradient-to-br from-blue-50 to-[#85cbcf]";
export const secondaryGradient = "bg-gradient-to-br from-amber-100 via-orange-50 to-rose-100";
export const dashboardGradient = " bg-gradient-to-br from-purple-50 via-amber-50 to-rose-100"
export const tableGradient = "bg-gradient-to-br from-[#007980] to-[#85cbcf]";
export const otherGradient = "bg-gradient-to-br from-[#85cbcf] via-amber-50 to-rose-100";
export const inactiveGradient = "bg-gradient-to-br from-gray-50 to-gray-100";
export const secondaryGreen = "#85cbcf";
export const primaryGreen = "#07C07E1A";
export const secondaryBorder = "border-gray-300";
export const orangeBorder = "border-orange-200";
export const alertOrange = "bg-gradient-to-r from-amber-500 to-rose-500";
export const alertOrange2 = "bg-gradient-to-r from-orange-500 to-amber-500";
export const darkGray ="#9ca3af";
export const lightBorder = "border-gray-200";
export const iconSecondary = "text-amber-600";
export const lightOrange = "#fde68a";
export const sidebarColor ="bg-gray-900";
export const sidebarActiveColor = "bg-gray-700"
export const sidebarTextActiveColor ="text-white";
export const sidebarTextColor ="text-gray-400"
